[package]
name = "rust-cli"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "rust-cli"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
